@startuml

title \n Awesome-WanAndroid \n

skinparam backgroundColor #AEFFFF
skinparam activityBackgroundColor peru
skinparam activityBarColor #green
skinparam activityBorderColor #ef5345
skinparam activityFontName Impact

rectangle View #lightGreen
rectangle MvpView #white
rectangle MvpPresenter #white
rectangle Presenter #lightGreen
rectangle AppDataManager #lightGreen
rectangle ApiHelper #white
rectangle AppApiHelper #lightGreen
rectangle PreferenceHelper #white
rectangle AppPreferenceHelper #lightGreen
rectangle DbHelper #white
rectangle AppDbHelper #lightGreen

View -- MvpView
View -r-> MvpPresenter
MvpPresenter -l-> View
MvpPresenter -- Presenter
Presenter -l-> MvpView
MvpView -r-> Presenter
Presenter -r-> AppDataManager
AppDataManager -l-> Presenter
AppDataManager -r-> PreferenceHelper
PreferenceHelper -l-> AppDataManager
PreferenceHelper -r- AppPreferenceHelper
AppDataManager -u-> ApiHelper
ApiHelper -d-> AppDataManager
ApiHelper -u-> AppApiHelper
AppDataManager -d-> DbHelper
DbHelper -u-> AppDataManager
DbHelper -d-> AppDbHelper







@enduml